source settings.sh

AUTOCONF_VERSION=2.72

module load perl

AUTOCONF_BUILD_PREFIX=$BUILD_PREFIX/autoconf-$AUTOCONF_VERSION
mkdir -p $AUTOCONF_BUILD_PREFIX

AUTOCONF_INSTALL_PREFIX=$INSTALL_PREFIX/autoconf-$AUTOCONF_VERSION
mkdir -p $AUTOCONF_INSTALL_PREFIX

AUTOCONF_MODULE_PREFIX=$MODULE_PREFIX/autoconf
mkdir -p $AUTOCONF_MODULE_PREFIX

cd $AUTOCONF_BUILD_PREFIX

wget https://mirrors.middlendian.com/gnu/autoconf/autoconf-$AUTOCONF_VERSION.tar.xz
tar -xvf autoconf-$AUTOCONF_VERSION.tar.xz
cd autoconf-$AUTOCONF_VERSION
./configure --prefix=$AUTOCONF_INSTALL_PREFIX
make -j64
make install

cd $AUTOCONF_INSTALL_PREFIX && rm -rf autoconf-$AUTOCONF_VERSION*

MODULE_TEMP_PATH=$MODULE_TEMP_PREFIX/$AUTOCONF_VERSION
cp $SETUP_PREFIX/modules/autoconf_module "$MODULE_TEMP_PATH"
sed -i "s|AUTOCONFVERSION|$AUTOCONF_VERSION|g" "$MODULE_TEMP_PATH"
sed -i "s|AUTOCONFROOT|$AUTOCONF_INSTALL_PREFIX|g" "$MODULE_TEMP_PATH"
mv "$MODULE_TEMP_PATH" "$AUTOCONF_MODULE_PREFIX/$AUTOCONF_VERSION.lua"
