source settings.sh

PERL_MAJOR_VERSION=5.0
PERL_VERSION=5.38.2

PERL_BUILD_PREFIX=$BUILD_PREFIX/perl-$PERL_VERSION
mkdir -p $PERL_BUILD_PREFIX

PERL_INSTALL_PREFIX=$INSTALL_PREFIX/perl-$PERL_VERSION
mkdir -p $PERL_INSTALL_PREFIX

PERL_MODULE_PREFIX=$MODULE_PREFIX/perl
mkdir -p $PERL_MODULE_PREFIX

module load gcc/$GCC_VERSION

CC=$(which gcc)

cd $PERL_BUILD_PREFIX

wget https://www.cpan.org/src/$PERL_MAJOR_VERSION/perl-$PERL_VERSION.tar.gz
tar -xzf perl-$PERL_VERSION.tar.gz && cd perl-$PERL_VERSION
./Configure -des -Dcc="$CC" -Dprefix=$PERL_INSTALL_PREFIX
make -j64 && make install

cd $PERL_BUILD_PREFIX && rm -rf perl-$PERL_VERSION*

MODULE_TEMP_PATH=$MODULE_TEMP_PREFIX/$PERL_VERSION
cp $SETUP_PREFIX/modules/perl_module "$MODULE_TEMP_PATH"
sed -i "s|PERLVERSION|$PERL_VERSION|g" "$MODULE_TEMP_PATH"
sed -i "s|GCCVERSION|$GCC_VERSION|g" "$MODULE_TEMP_PATH"
sed -i "s|PERLROOT|$PERL_INSTALL_PREFIX|g" "$MODULE_TEMP_PATH"
mv "$MODULE_TEMP_PATH" "$PERL_MODULE_PREFIX/$PERL_VERSION.lua"
