#!/bin/bash

source settings.sh

JULIA_VERSION=1.10.5
BLOQADE_JULIA_VERSION=0.2.4

module load julia

BLOQADE_JULIA_BUILD_PREFIX=$BUILD_PREFIX/jl-${JULIA_VERSION}-bloqade
mkdir -p $BLOQADE_JULIA_BUILD_PREFIX
BLOQADE_JULIA_INSTALL_PREFIX=$INSTALL_PREFIX/jl-${JULIA_VERSION}-bloqade
mkdir -p $BLOQADE_JULIA_INSTALL_PREFIX
BLOQADE_JULIA_MODULE_PREFIX=$MODULE_PREFIX/jl-${JULIA_VERSION}-bloqade
mkdir -p $BLOQADE_JULIA_MODULE_PREFIX


export JULIA_PROJECT=$BLOQADE_JULIA_INSTALL_PREFIX/site-project
export JULIA_DEPOT_PATH=$BLOQADE_JULIA_INSTALL_PREFIX/site-depot:$JULIA_DEPOT_PATH
export JULIA_LOAD_PATH=$JULIA_PROJECT:$JULIA_LOAD_PATH
echo $JULIA_DEPOT_PATH
echo $JULIA_LOAD_PATH

julia -e "using Pkg; Pkg.add(PackageSpec(name = \"Bloqade\", version = \"${BLOQADE_JULIA_VERSION}\"))"

MODULE_TEMP_PATH=$MODULE_TEMP_PREFIX/$BLOQADE_JULIA_VERSION
cp $SETUP_PREFIX/modules/bloqade_julia_module "$MODULE_TEMP_PATH"
sed -i "s|BLOQADEJULIAVERSION|$BLOQADE_JULIA_VERSION|g" "$MODULE_TEMP_PATH"
sed -i "s|JULIAVERSION|$JULIA_VERSION|g" "$MODULE_TEMP_PATH"
sed -i "s|BLOQADEJULIADEPOTPATH|$BLOQADE_JULIA_INSTALL_PREFIX/site-depot|g" "$MODULE_TEMP_PATH"
sed -i "s|BLOQADEJULIAPROJECTPATH|$JULIA_PROJECT|g" "$MODULE_TEMP_PATH"

mv $MODULE_TEMP_PATH $BLOQADE_JULIA_MODULE_PREFIX/$BLOQADE_JULIA_VERSION.lua



